name: test_2

on:
  workflow_dispatch:

concurrency:
  test

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: sleep
        run: sleep 30